use standard errors in examples
wallet-standard/wallet-standard pull request #55
Opened 2022-10-12 20:54 UTC by olistic

This PR uses the new standard errors (#54) in the examples.

2024-08-12 20:15 UTC, olistic commented
@jordaaash @steveluscher is this still a valuable contribution?

2024-09-02 00:41 UTC, steveluscher commented
Sounds great! Add these codes to https://github.com/wallet-standard/wallet-standard/tree/master/packages/core/errors and use them here.

2024-09-02 00:42 UTC, steveluscher requested changes
Sounds great! Add these codes to https://github.com/wallet-standard/wallet-standard/tree/master/packages/core/errors and use them here.

2024-09-16 05:34 UTC, olistic commented on packages/core/errors/src/codes.ts
> +export const WALLET_STANDARD_ERROR__USER__REQUEST_REJECTED = 4001000 as const;
@steveluscher this was originally 4001, inspired by [EIP-1193's errors](https://eips.ethereum.org/EIPS/eip-1193#provider-errors). Now it's completely arbitrary. Let me know if you want to change it.

2024-09-16 05:35 UTC, olistic commented
> Sounds great! Add these codes to https://github.com/wallet-standard/wallet-standard/tree/master/packages/core/errors and use them here.

Done.

2024-10-22 22:53 UTC, steveluscher commented
![Added via Giphy](https://media0.giphy.com/media/26gsjCZpPolPr3sBy/giphy.gif?cid=c94877437fda465fdqty4daqqxveae3sccyq8cbafpon57pp&ep=v1_gifs_search&rid=giphy.gif&ct=g)

Did we lose the changes to `packages/example/dapp/src/pages/Connect.tsx` in your latest update? Feel free to add that back in a separate PR if you like.

2024-10-22 22:53 UTC, merged